name: Continuous Integration

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - uses: actions/cache@v4
        env:
          cache-name: rebar3
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ci-${{runner.os}}-${{env.cache-name}}-${{hashFiles('mise.toml', 'rebar.lock')}}
          restore-keys: |
            ci-${{runner.os}}-${{env.cache-name}}

      - uses: actions/cache@v4
        env:
          cache-name: tailwind
        with:
          path: |
            priv/styles/node_modules
          key: ci-${{runner.os}}-${{env.cache-name}}-${{hashFiles('priv/styles/yarn.lock')}}

      - name: Verify
        run: mise run --output=keep-order verify

      - name: Test
        run: mise run --output=keep-order test
