name: Continuous Integration

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        env:
          cache-name: rebar3
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ci-${{runner.os}}-${{env.cache-name}}-${{hashFiles('mise.toml', 'rebar.lock')}}
          restore-keys: |
            ci-${{runner.os}}-${{env.cache-name}}

      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        env:
          cache-name: tailwind
        with:
          path: |
            priv/styles/node_modules
          key: ci-${{runner.os}}-${{env.cache-name}}-${{hashFiles('priv/styles/yarn.lock')}}

      - name: Verify
        run: mise run --output=keep-order verify

      - name: Test
        run: mise run --output=keep-order test
